### ISSUE TITLE
how install it ?

### ISSUE THREAD

**Issue by sergiomb2** [gammu/python-gammu#1]
diff gammu-1.34.0/python/ python-gammu-2.1/ -rq
shows: 
Only in gammu-1.34.0/python/: CMakeLists.txt
Only in gammu-1.34.0/python/: CMakeTests.txt

So I think, it can't be installed as in gammu-1.34 ...

**Comment by nijel** [comment]
I've updated README to cover installation, but it's standard like any other Python module: https://github.com/gammu/python-gammu/blob/master/README.rst#installing
