### ISSUE TITLE
Can't get dial voice status

### ISSUE THREAD

**Issue by vicgordienko** [gammu/python-gammu#10]
I use function DialVoice(Number) for dial voice, I get only Status': 'CallEnd' via SetIncomingCallback.
How I can get dial status (BUSY, NO DIALTONE, NO CARRIER, NA ANSWER, CONNECT) ? 
gammu version: ('1.33.0', '2.6', '1.37.4')

**Comment by nijel** [comment]
The at driver currently doesn't expose more detailed information. (And CallEnd is actually NO CARRIER)
