### ISSUE TITLE
Can't get USSD response

### ISSUE THREAD

**Issue by vicgordienko** [gammu/python-gammu#12]
I am using gammu worker (version ('1.37.91', '2.7', '1.37.91')) and I want check balance, with
`_worker.enqueue('DialService', {'Number': '*111#'})`

But always:
-> DialService completed 100% with error ERR_TIMEOUT , return value:
None

Log: [gsm.txt](https://github.com/gammu/python-gammu/files/560497/gsm.txt)

In the log I have found out than modem received "AT+CUSD=0,"_111#",15"
I tried to send direct "AT+CUSD=0,"_111#",15" and receive only OK without balance status. Then I tried to send AT+CUSD=**1**,"*111#",15 and I saw balance status.

AT+CUSD cmd description:
.....
Defined values:
0 disable the result code presentation in the TA
1 enable the result code presentation in the TA
2 cancel session (not applicable to read command response)

So I think the problem in the incorrect CUSD parameter. 

Could you please check it?

Thank you!

**Comment by nijel** [comment]
You're missing call to `SetIncomingUSSD` to enable USSD processing in Gammu.

**Comment by vicgordienko** [comment]
Thank you!
Fixed it. But I still get ERR_TIMEOUT.
-> DialService completed 100% with error ERR_TIMEOUT , return value:
None
python-gammu: WARNING: Adding USSD to queue, position 0

Received incoming event type USSD, data:
{'Status': 'NoActionNeeded', 'Text': u'Balans 0.00hrn, bonus 0.00hrn.\n\n'}

[gsm.txt](https://github.com/gammu/python-gammu/files/562524/gsm.txt)
