### ISSUE TITLE
unicode characters don't show up in sms

### ISSUE THREAD

**Issue by jottunn** [gammu/python-gammu#19]
whenever i send unicode characters in an sms they either don't show up or get replaced by similar nonunicode ones

this is what i use to send the sms

```
def send_sms(recipients, sms_text):
    sm = gammu.StateMachine()
    sm.ReadConfig()
    sm.Init()

    for number, language in recipients:
        smsinfo = {
            'Class': -1,
            'Unicode': True,
            'Entries': [
                {
                    'ID': 'ConcatenatedTextLong',
                    'Buffer': sms_text
                }
            ]}
        encoded = gammu.EncodeSMS(smsinfo)
        try:
            for message in encoded:
                message['SMSC'] = {'Location': 1}
                message['Number'] = number
                sm.SendSMS(message)
            logger.info('sent to ' + number)
        except Exception as e:
            logger.error(e)
```

**Comment by nijel** [comment]
In my tests it works just fine. What versions do you use?

**Comment by jottunn** [comment]
Python 3.5.2
python-gammu==2.5
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-77-generic x86_64)

Example:
```
import gammu

sm = gammu.StateMachine()
sm.ReadConfig()
sm.Init()

message = {
    'Text': 'ăîâțș', 
    'SMSC': {'Location': 1},
    'Number': 'my number',
}

sm.SendSMS(message)
```
received sms looks like this: aia??

**Comment by nijel** [comment]
In this case it's expected as you didn't specify encoding and default GSM is used, you should add `'Coding': 'Unicode_No_Compression'` to the message dict here. But it should be there from EncodeSMS in case you've specified Unicode in flags for it...

I can see no related fixes in newer versions unless you're not sending emojis or some other chars which can't be encoded in UCS-2.

**Comment by jottunn** [comment]
you are right, adding 'Coding': 'Unicode_No_Compression' to the message dict did the trick for short messages, however if I do the same thing for multipart sms, there is still no change

```
def send_sms(recipients, sms_text):
    sm = gammu.StateMachine()
    sm.ReadConfig()
    sm.Init()

    for number, language in recipients:
        smsinfo = {
            'Class': -1,
            'Unicode': True,
            'Entries': [
                {
                    'ID': 'ConcatenatedTextLong',
                    'Buffer': sms_text
                }
            ]}
        encoded = gammu.EncodeSMS(smsinfo)
        try:
            for message in encoded:
                message['SMSC'] = {'Location': 1}
                message['Number'] = number
                message['Coding'] = 'Unicode_No_Compression'
                sm.SendSMS(message)
            logger.info('sent to ' + number)
        except Exception as e:
            logger.error(e)

send_sms([numbers], 'ăîâșț') 
``` 
still sends out 'aia??'

**Comment by nijel** [comment]
It should not be needed there .. What's content of encoded?

**Comment by jottunn** [comment]
looked into it a bit more, when i pulled out the sms sending part from my app and used it standalone everything worked as intended, it was an encoding issue on my part.

thanks a bunch for helping out.
