### ISSUE TITLE
python3 support needed

### ISSUE THREAD

**Issue by abadger1406** [gammu/python-gammu#20]
```
# sudo apt-get install gammu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gammu is already the newest version (1.38.1-1+deb.cihar.com~yakkety.1).
0 to upgrade, 0 to newly install, 0 to remove and 26 not to upgrade.
root@crowthorne:/home/dave/Downloads/python-gammu-2.8# sudo pip-3.2 install python-gammu
sudo: pip-3.2: command not found
root@crowthorne:/home/dave/Downloads/python-gammu-2.8# sudo pip-3.2 install python-gammu
sudo: pip-3.2: command not found
root@crowthorne:/home/dave/Downloads/python-gammu-2.8# sudo pip3.2 install python-gammu
sudo: pip3.2: command not found
root@crowthorne:/home/dave/Downloads/python-gammu-2.8# sudo pip3 install python-gammu
Collecting python-gammu
  Using cached python-gammu-2.8.tar.gz
    Complete output from command python setup.py egg_info:
    Package gammu was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gammu.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gammu' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-v8lls__o/python-gammu/setup.py", line 110, in <module>
        check_minimum_gammu_version()
      File "/tmp/pip-build-v8lls__o/python-gammu/setup.py", line 45, in check_minimum_gammu_version
        "gammu"
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'pkg-config' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v8lls__o/python-gammu/
# 
```

**Comment by abadger1406** [comment]
# pwd
/home/dave/Downloads/python-gammu-2.8
# ls
AUTHORS  examples  include      NEWS.rst  python_gammu.egg-info  setup.cfg  test
COPYING  gammu     MANIFEST.in  PKG-INFO  README.rst             setup.py
# ./setup.py build
Package gammu was not found in the pkg-config search path.
Perhaps you should add the directory containing `gammu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gammu' found
Traceback (most recent call last):
  File "./setup.py", line 110, in <module>
    check_minimum_gammu_version()
  File "./setup.py", line 45, in check_minimum_gammu_version
    "gammu"
  File "/usr/lib/python2.7/distutils/spawn.py", line 38, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/spawn.py", line 192, in _spawn_posix
    (cmd, exit_status)
distutils.errors.DistutilsExecError: command 'pkg-config' failed with exit status 1
#

**Comment by nijel** [comment]
You need to install [requirements](https://github.com/gammu/python-gammu#requirements) first. It works just fine on Python 3.

**Comment by abadger1406** [comment]
dave@crowthorne:/home/ap/src$ sudo apt-get install gammu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gammu is already the newest version (1.38.1-1+deb.cihar.com~yakkety.1).
0 to upgrade, 0 to newly install, 0 to remove and 69 not to upgrade.
dave@crowthorne:/home/ap/src$ sudo apt-get install libgammu-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libgammu-dev : Depends: libgammu8 (= 1.38.1-1) but 1.38.1-1+deb.cihar.com~yakkety.1 is to be installed
                Depends: libgsmsd8 (= 1.38.1-1) but 1.38.1-1+deb.cihar.com~yakkety.1 is to be installed
E: Unable to correct problems, you have held broken packages.
dave@crowthorne:/home/ap/src$ uname -a
Linux crowthorne 4.10.0-041000-generic #201702191831 SMP Sun Feb 19 23:33:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abadger1406** [comment]
libgammu-dev : Depends: libgammu8 (= 1.38.1-1) but 1.38.1-1+deb.cihar.com~yakkety.1 is to be installed

**Comment by nijel** [comment]
Looks like you're mixing distro packages with PPA ones, did you manually install them?
