### ISSUE TITLE
Catching gammu.ERR_DEVICENOTEXIST

### ISSUE THREAD

**Issue by Hipska** [gammu/python-gammu#25]
Hi,

```python
except gammu.ERR_DEVICENOTEXIST as e:
  print "Cannot open modem: {error}".format(error=e)
```
Returns:
> Cannot open modem: {'Text': "Error opening device, it doesn't exist.", 'Code': 4, 'Where': 'Init'}

I tried to use `e.Text` and `e['Text']`, but both seem not to work. How can I get the text from the exception? Or let the exception print only the text without other fields..

**Comment by nijel** [comment]
The dictionary with details should be accessible as `e.value`.
