### ISSUE TITLE
Connection state?

### ISSUE THREAD

**Issue by NicoHood** [gammu/python-gammu#30]
Hi,
I want to write a reliable mqtt sms deamon that always reconnects when the phone connection is lost. Is there a way to query the phone state? I found no way in the API to query for the phone state. There must be some AT command that responds with a simple OK, cant we use this?

I want to use this information to either close or reopen the connection. Do you have any example or suggestion to build such a relyable deamon?

**Comment by nijel** [comment]
The SMSD already does this. It periodically checks for network status.

**Comment by NicoHood** [comment]
But the smsd requires to store sms as files, which I do not want. What command can I use to check the connection status?

**Comment by nijel** [comment]
You can also store them in a database, see [supported backends](https://wammu.eu/docs/manual/smsd/backends.html).

Anyway it just does GetNetworkStatus.
