### ISSUE TITLE
Delete only one SMS

### ISSUE THREAD

**Issue by jrpetrolla** [gammu/python-gammu#39]
The command line gammu deleteallsms works but, I can not do it directly in my python code, and that's the problem, because it's an robot which responds automatically, and when sim is full the robot cannot do anymore it's job! If I interrupt the process to launch the os gammu deleteallsms command line, I risk to lose an arriving message. I would have preferred to delete the SMS one by one.

[2020-07-04 22:02:01,095] ERROR in app: Exception on /sms [DELETE]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./run.py", line 55, in delete
    return machine.DeleteSMS(Folder=int(args['folder']),Location=int(args['location']))
gammu.ERR_MEMORY_NOT_AVAILABLE: {'Text': 'The type of memory is not available or has been disabled.', 'Where': 'DeleteSMS', 'Code': 81}
192.168.1.10 - - [04/Jul/2020 22:02:01] "DELETE /sms HTTP/1.1" 500 -

System: Raspbian GNU/Linux 10 (buster) 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
Python 3.7.3 / python-gammu   3.0

**Comment by bohns** [comment]
I have the same issue:

gammu 1.42.0
python-gammu from https://github.com/kstuart/python-gammu/tree/fix/deletesms
   @kstuart

```
Name: python-gammu
Version: 3.1
Summary: Gammu bindings
Home-page: https://wammu.eu/python-gammu/
Author: Michal Cihar
Author-email: michal@cihar.com
License: GPLv2+
Location: /usr/local/lib/python3.7/dist-packages/python_gammu-3.1-py3.7-linux-armv7l.egg
Requires: 
Required-by: 
```

Code:
`sm.DeleteSMS(0,messagedata['Location'])`

produces:

```
Traceback (most recent call last):
  File "./processTexts.py", line 110, in <module>
    daemon.start()
  File "/home/pi/Desktop/git/SMBCode/relay_project/Daemon.py", line 85, in start
    self.run()
  File "./processTexts.py", line 86, in run
    sm.DeleteSMS(1,messagedata['Location'])
gammu.ERR_MEMORY_NOT_AVAILABLE: {'Text': u'The type of memory is not available or has been disabled.', 'Code': 81, 'Where': 'DeleteSMS'}
```

gammu log file:

```
Fri 2020/10/23 11:11:23: [Gammu - 1.42.0]
Fri 2020/10/23 11:11:23: [Connection - "at19200"]
Fri 2020/10/23 11:11:23: [Connection index - 0]
Fri 2020/10/23 11:11:23: [Model type - ""]
Fri 2020/10/23 11:11:23: [Device - "/dev/ttyUSB1"]
Fri 2020/10/23 11:11:23: [Running on - Linux, kernel 5.4.51-v7l+ (#1333 SMP Mon Aug 10 16:51:40 BST 2020)]
Fri 2020/10/23 11:11:23: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Fri 2020/10/23 11:11:23: Setting speed to 19200
Fri 2020/10/23 11:11:23: [Module - "auto"]

...
Fri 2020/10/23 11:11:27: Entering GSM_DeleteSMS
Fri 2020/10/23 11:11:27: Location = 1, Folder = 0
Fri 2020/10/23 11:11:27: SMS folder 0 & location 1 -> ATGEN folder 1 & location 1
Fri 2020/10/23 11:11:27: Requested memory not available for reading: XX (-1238362640)
Fri 2020/10/23 11:11:27: GSM_DeleteSMS failed with error MEMORY_NOT_AVAILABLE[81]: The type of memory is not available or has been disabled.
Fri 2020/10/23 11:11:27: Leaving GSM_DeleteSMS
```
Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

**Comment by bohns** [comment]
See, I don't know why this would be a python-gammu issue... if I fall back to gammu 1.38 everything works just fine. gammu 1.40 broke it.

**Comment by kstuart** [comment]
@bohns, support for SR memory was added to Gammu which has introduced new code paths, and checks need to made for the requested memory type, e.g: https://github.com/gammu/gammu/blob/0d5326db45acb1b4ab88d0bbcb61da4b04344b99/libgammu/phone/at/at-sms.c#L490

Unfortunately the code to delete an SMS (both in gammu cli and this code) passes a partially initialized data structure to `GSM_DeleteSMS` which obviously is fragile and best avoided, you can see [here](https://github.com/gammu/python-gammu/blob/ad2b766e1d0922ffa411067b05190dde10c890ee/gammu/src/gammu.c#L2723) where python-gammu creates a `GSM_SMSMessage` variable `sms` and does not initialize it to a known state before passing it to `GSM_DeleteSMS` (it does set the SMS `Folder` and `Location` but value for `Memory` is uninitialize so could contain anything, this causes the updated Gammu code to fail or be unpredictable (garbage in garbage out).

You can see in my quick [attempt to fix](https://github.com/kstuart/python-gammu/commit/fa53546bd02ce60abb685b24b8d925aac7077caf#diff-f20329b38107530b9c3c201b0ed3614a52bb92e978a707712a98cf9c0e629fd5R2718) I've zero initialized the `sms` structure which aught to work, however I'm not familiar with python or have to tooling to analyze/debug python code.

I hope that helps explain what I currently believe is the likely issue.

**Comment by ocalvo** [comment]
I will test this change and report back.

**Comment by ocalvo** [comment]
@kstuart My first test resulted in a positive result. I can now delete SMS messages from python. I will proceed to undo the change see that the problem repro again and then do the change again to ensure it does in fact fixes the problem.

**Comment by ocalvo** [comment]
I have created a PR #45 with the fix. Thanks @kstuart.
@nijel Can you merge this change? This is blocking the SMS integration in homeassistant.
