### ISSUE TITLE
Can't connect to the phone after remove usb-cable

### ISSUE THREAD

**Issue by nesergen** [gammu/python-gammu#8]
Xubuntu 16.04, Gammu 1.37.4, python-gammu 2.6, Philips x5500
After start my programm can initiate and terminate connection many times.
But after extrim-disconnect as removing the usb-cable and inserting it back connection can't be established. Error gammu.ERR_DEVICENOTEXIST is occure. After restart the phone connection not work aswell. After restart the computer connection work well. Where is the problem? Same problem does appear in Wammu. In wammu connection may be established after re-creating new config for telephone.

This is config file after four extrim-disconnection and re-creating new config:

`>[gammu]
connection = at
logformat = nothing
port = /dev/ttyACM0
synchronizetime = no
name= all_in_one
model=

[gammu1]
port=/dev/ttyACM0
connection=at115200
name=first
model=

[gammu2]
port=/dev/ttyUSB0
connection=at115200
name=second
model=

[gammu3]
port=/dev/ttyUSB1
connection=at115200
name=third

[gammu4]
port=/dev/ttyUSB0
connection=at115200
name=fourth

`

**Comment by nijel** [comment]
Probably there is different device name after insertion, see https://wammu.eu/docs/manual/faq/general.html#device-name-always-changes-on-linux-how-to-solve-that

**Comment by nesergen** [comment]
Yes, the problem was that  the phone was connected to different ports after re-connection to the cable (`/dev/ttyUSB* `or  `/dev/ttyACM*` )
To solve this I have created rule in the `/etc/udev/rules.d/`:
```
# udev rule to give users access to USB device to be used by Gammu

ACTION=="add", SUBSYSTEMS=="usb", ATTRS{idVendor}=="0e8d", ATTRS{idProduct}=="0003", SYMLINK+="phone5500"
```
After that I created section in file `/.gammurc` : 
```
[gammu]

device=/dev/phone5500
connection=at
synchronizetime = no
```
Now my phone work with any port.

**Comment by nesergen** [comment]
Set the issue like SOLVED, please.
